package com.energicube.eno.pattern.model;
// Generated 2013-8-21 16:23:12 by Hibernate Tools 3.4.0.CR1


import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.util.Date;

/**
 * UcFactorRecord generated by hbm2java
 */
@Entity
@Table(name = "UC_factorRecord"
        , schema = "dbo"
)
public class UcFactorRecord implements java.io.Serializable {


    private String id;
    @org.codehaus.jackson.annotate.JsonBackReference
    @com.fasterxml.jackson.annotation.JsonBackReference
    private UcPatternRecord ucPatternRecord;
    private String name;
    private String minValue;
    private String maxValue;
    private String description;
    private String factorType;
    private Date startDate;
    private Date endDate;

    public UcFactorRecord() {
    }


    public UcFactorRecord(String id) {
        this.id = id;
    }

    public UcFactorRecord(String id, UcPatternRecord ucPatternRecord, String name, String minValue, String maxValue, String description, String factorType, Date startDate, Date endDate) {
        this.id = id;
        this.ucPatternRecord = ucPatternRecord;
        this.name = name;
        this.minValue = minValue;
        this.maxValue = maxValue;
        this.description = description;
        this.factorType = factorType;
        this.startDate = startDate;
        this.endDate = endDate;
    }

    @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
    @Column(name = "id", unique = true, nullable = false, length = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY,cascade = CascadeType.DETACH)
    @JoinColumn(name = "patternRecordId")
    public UcPatternRecord getUcPatternRecord() {
        return this.ucPatternRecord;
    }

    public void setUcPatternRecord(UcPatternRecord ucPatternRecord) {
        this.ucPatternRecord = ucPatternRecord;
    }


    @Column(name = "name", length = 60)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }


    @Column(name = "minValue", length = 60)
    public String getMinValue() {
        return this.minValue;
    }

    public void setMinValue(String minValue) {
        this.minValue = minValue;
    }


    @Column(name = "maxValue", length = 60)
    public String getMaxValue() {
        return this.maxValue;
    }

    public void setMaxValue(String maxValue) {
        this.maxValue = maxValue;
    }


    @Column(name = "description", length = 60)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }


    @Column(name = "factorType", length = 4)
    public String getFactorType() {
        return this.factorType;
    }

    public void setFactorType(String factorType) {
        this.factorType = factorType;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "startDate", length = 23)
    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "endDate", length = 23)
    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }


}


