package com.energicube.eno.pattern.model;
// Generated 2013-8-21 16:23:12 by Hibernate Tools 3.4.0.CR1


import com.energicube.eno.calendar.model.UcCalendar;
import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UcPatternRecord generated by hbm2java
 */
@Entity
@Table(name = "UC_patternRecord"
        , schema = "dbo"
)
public class UcPatternRecord implements java.io.Serializable {


    private String id;
    private String version;
    @org.codehaus.jackson.annotate.JsonBackReference
    @com.fasterxml.jackson.annotation.JsonBackReference
    private UcCalendar ucCalendar;
    private String systemId;
    private String patternId;
    private String patternName;
    private String patternType;
    private Date startTime;
    private Date endTime;
    private String parentId;
    private Integer baseTime;
    private Integer offsetTime;
    private String createUser;
    private Date createDate;
    private String systemSecond;
    private String systemThree;
    private String isNew;
    private Set<UcFactorRecord> ucFactorRecords = new HashSet<UcFactorRecord>(0);
    private Set<UcDeviceRecord> ucDeviceRecords = new HashSet<UcDeviceRecord>(0);

    public UcPatternRecord() {
    }


    public UcPatternRecord(String id) {
        this.id = id;
    }

    public UcPatternRecord(String id, UcCalendar ucCalendar, String systemId, String patternId, String patternName, String patternType, Date startTime, Date endTime, String parentId, Integer baseTime, Integer offsetTime, String createUser, Date createDate, Set<UcFactorRecord> ucFactorRecords, Set<UcDeviceRecord> ucDeviceRecords) {
        this.id = id;
        this.ucCalendar = ucCalendar;
        this.systemId = systemId;
        this.patternId = patternId;
        this.patternName = patternName;
        this.patternType = patternType;
        this.startTime = startTime;
        this.endTime = endTime;
        this.parentId = parentId;
        this.baseTime = baseTime;
        this.offsetTime = offsetTime;
        this.createUser = createUser;
        this.createDate = createDate;
        this.ucFactorRecords = ucFactorRecords;
        this.ucDeviceRecords = ucDeviceRecords;
    }

    @Id

    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
    @Column(name = "id", unique = true, nullable = false, length = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "version", length = 50)
    public String getVersion() {
        return this.version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "calendarId")
    public UcCalendar getUcCalendar() {
        return this.ucCalendar;
    }

    public void setUcCalendar(UcCalendar ucCalendar) {
        this.ucCalendar = ucCalendar;
    }


    @Column(name = "systemId", length = 36)
    public String getSystemId() {
        return this.systemId;
    }

    public void setSystemId(String systemId) {
        this.systemId = systemId;
    }


    @Column(name = "patternId", length = 36)
    public String getPatternId() {
        return this.patternId;
    }

    public void setPatternId(String patternId) {
        this.patternId = patternId;
    }


    @Column(name = "patternName", length = 200)
    public String getPatternName() {
        return this.patternName;
    }

    public void setPatternName(String patternName) {
        this.patternName = patternName;
    }


    @Column(name = "patternType", length = 4)
    public String getPatternType() {
        return this.patternType;
    }

    public void setPatternType(String patternType) {
        this.patternType = patternType;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "startTime", length = 23)
    public Date getStartTime() {
        return this.startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "endTime", length = 23)
    public Date getEndTime() {
        return this.endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }


    @Column(name = "parentId", length = 36)
    public String getParentId() {
        return this.parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }


    @Column(name = "baseTime")
    public Integer getBaseTime() {
        return this.baseTime;
    }

    public void setBaseTime(Integer baseTime) {
        this.baseTime = baseTime;
    }


    @Column(name = "offsetTime")
    public Integer getOffsetTime() {
        return this.offsetTime;
    }

    public void setOffsetTime(Integer offsetTime) {
        this.offsetTime = offsetTime;
    }


    @Column(name = "createUser", length = 50)
    public String getCreateUser() {
        return this.createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "createDate", length = 23)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ucPatternRecord",  cascade ={CascadeType.REMOVE,CascadeType.DETACH})
    public Set<UcFactorRecord> getUcFactorRecords() {
        return this.ucFactorRecords;
    }

    public void setUcFactorRecords(Set<UcFactorRecord> ucFactorRecords) {
        this.ucFactorRecords = ucFactorRecords;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ucPatternRecord",  cascade ={CascadeType.REMOVE,CascadeType.DETACH})
    public Set<UcDeviceRecord> getUcDeviceRecords() {
        return this.ucDeviceRecords;
    }

    public void setUcDeviceRecords(Set<UcDeviceRecord> ucDeviceRecords) {
        this.ucDeviceRecords = ucDeviceRecords;
    }


    @Column(name = "systemSecond", length = 36)
    public String getSystemSecond() {
        return systemSecond;
    }

    public void setSystemSecond(String systemSecond) {
        this.systemSecond = systemSecond;
    }

    @Column(name = "systemThree", length = 36)
    public String getSystemThree() {
        return systemThree;
    }

    public void setSystemThree(String systemThree) {
        this.systemThree = systemThree;
    }

    @Column(name = "isNew", length = 4)
    public String getIsNew() {
        return isNew;
    }

    public void setIsNew(String aNew) {
        isNew = aNew;
    }
}


