package com.energicube.eno.pattern.model;
// Generated 2013-8-21 16:23:12 by Hibernate Tools 3.4.0.CR1


import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * UcSysFactor generated by hbm2java
 */
@Entity
@Table(name = "UC_sysFactor"
        , schema = "dbo"
)
public class UcSysFactor implements java.io.Serializable {


    private String id;
    private UcFactor ucFactor;
    private String description;
    private String systemId;

    public UcSysFactor() {
    }


    public UcSysFactor(String id) {
        this.id = id;
    }

    public UcSysFactor(String id, UcFactor ucFactor, String description, String systemId) {
        this.id = id;
        this.ucFactor = ucFactor;
        this.description = description;
        this.systemId = systemId;
    }

    @Id

    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
    @Column(name = "id", unique = true, nullable = false, length = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY,cascade = CascadeType.DETACH)
    @JoinColumn(name = "factorId")
    public UcFactor getUcFactor() {
        return this.ucFactor;
    }

    public void setUcFactor(UcFactor ucFactor) {
        this.ucFactor = ucFactor;
    }


    @Column(name = "description", length = 60)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }


    @Column(name = "systemId", length = 36)
    public String getSystemId() {
        return this.systemId;
    }

    public void setSystemId(String systemId) {
        this.systemId = systemId;
    }


}


