package com.energicube.eno.monitor.model;

// Generated 2013-9-11 15:34:11 by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * Securityrestrict generated by hbm2java
 */
@Entity
@Table(name = "SECURITYRESTRICT")
public class SecurityRrestrict implements java.io.Serializable {

    private long securityrestrictid;
    private String groupname;
    private String objectname;
    private Long ownerid;
    private String policyname;
    private String restriction;
    private String restrictnum;

    public SecurityRrestrict() {
    }

    public SecurityRrestrict(long securityrestrictid) {
        this.securityrestrictid = securityrestrictid;
    }

    public SecurityRrestrict(long securityrestrictid, String groupname,
                             String objectname, Long ownerid, String policyname,
                             String restriction, String restrictnum) {
        this.securityrestrictid = securityrestrictid;
        this.groupname = groupname;
        this.objectname = objectname;
        this.ownerid = ownerid;
        this.policyname = policyname;
        this.restriction = restriction;
        this.restrictnum = restrictnum;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "SECURITYRESTRICTID", unique = true, nullable = false)
    public long getSecurityrestrictid() {
        return this.securityrestrictid;
    }

    public void setSecurityrestrictid(long securityrestrictid) {
        this.securityrestrictid = securityrestrictid;
    }

    @Column(name = "GROUPNAME", length = 30)
    public String getGroupname() {
        return this.groupname;
    }

    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }

    @Column(name = "OBJECTNAME", length = 30)
    public String getObjectname() {
        return this.objectname;
    }

    public void setObjectname(String objectname) {
        this.objectname = objectname;
    }

    @Column(name = "OWNERID")
    public Long getOwnerid() {
        return this.ownerid;
    }

    public void setOwnerid(Long ownerid) {
        this.ownerid = ownerid;
    }

    @Column(name = "POLICYNAME", length = 30)
    public String getPolicyname() {
        return this.policyname;
    }

    public void setPolicyname(String policyname) {
        this.policyname = policyname;
    }

    @Column(name = "RESTRICTION", length = 20)
    public String getRestriction() {
        return this.restriction;
    }

    public void setRestriction(String restriction) {
        this.restriction = restriction;
    }

    @Column(name = "RESTRICTNUM", length = 12)
    public String getRestrictnum() {
        return this.restrictnum;
    }

    public void setRestrictnum(String restrictnum) {
        this.restrictnum = restrictnum;
    }

}
