package com.energicube.eno.calendar.model;

import com.energicube.eno.pattern.model.UcPatternRecord;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UcCalendar generated by hbm2java
 */
@Entity
@Table(name = "UC_calendar"
        , schema = "zclfsys"
)
public class UcCalendar implements java.io.Serializable {


    private String id;
    private String calendarYear;
    private String calendarMonth;
    private String calendarDay;
    private String weekYear;
    private String lunarCalendar;
    private String lunarYear;
    private String lunarMonth;
    private String lunarDay;
    private String dayWeek;
    private Date openTime;
    private Date closeTime;
    private String siteId;
    private String orgId;
    private Set<UcWeather> ucWeathers = new HashSet<UcWeather>(0);
    private Set<UcHoliday> ucHolidays = new HashSet<UcHoliday>(0);
    private Set<UcPatternRecord> ucPatternRecords = new HashSet<UcPatternRecord>(0);

    public UcCalendar() {
    }


    public UcCalendar(String id) {
        this.id = id;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false, length = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }


    @Column(name = "calendarYear", length = 10)
    public String getCalendarYear() {
        return this.calendarYear;
    }

    public void setCalendarYear(String calendarYear) {
        this.calendarYear = calendarYear;
    }


    @Column(name = "calendarMonth", length = 4)
    public String getCalendarMonth() {
        return this.calendarMonth;
    }

    public void setCalendarMonth(String calendarMonth) {
        this.calendarMonth = calendarMonth;
    }


    @Column(name = "calendarDay", length = 4)
    public String getCalendarDay() {
        return this.calendarDay;
    }

    public void setCalendarDay(String calendarDay) {
        this.calendarDay = calendarDay;
    }


    @Column(name = "weekYear", length = 10)
    public String getWeekYear() {
        return this.weekYear;
    }

    public void setWeekYear(String weekYear) {
        this.weekYear = weekYear;
    }


    @Column(name = "lunarCalendar", length = 30)
    public String getLunarCalendar() {
        return this.lunarCalendar;
    }

    public void setLunarCalendar(String lunarCalendar) {
        this.lunarCalendar = lunarCalendar;
    }

    @Column(name = "lunarYear", length = 10)
    public String getLunarYear() {
        return lunarYear;
    }

    public void setLunarYear(String lunarYear) {
        this.lunarYear = lunarYear;
    }

    @Column(name = "lunarMonth", length = 4)
    public String getLunarMonth() {
        return lunarMonth;
    }

    public void setLunarMonth(String lunarMonth) {
        this.lunarMonth = lunarMonth;
    }

    @Column(name = "lunarDay", length = 4)
    public String getLunarDay() {
        return lunarDay;
    }

    public void setLunarDay(String lunarDay) {
        this.lunarDay = lunarDay;
    }

    @Column(name = "dayWeek", length = 10)
    public String getDayWeek() {
        return this.dayWeek;
    }

    public void setDayWeek(String dayWeek) {
        this.dayWeek = dayWeek;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "openTime", length = 16)
    public Date getOpenTime() {
        return this.openTime;
    }

    public void setOpenTime(Date openTime) {
        this.openTime = openTime;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "closeTime", length = 16)
    public Date getCloseTime() {
        return this.closeTime;
    }

    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ucCalendar",  cascade ={CascadeType.REMOVE})
    public Set<UcWeather> getUcWeathers() {
        return this.ucWeathers;
    }

    public void setUcWeathers(Set<UcWeather> ucWeathers) {
        this.ucWeathers = ucWeathers;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ucCalendar",  cascade ={CascadeType.REMOVE})
    public Set<UcHoliday> getUcHolidays() {
        return this.ucHolidays;
    }

    public void setUcHolidays(Set<UcHoliday> ucHolidays) {
        this.ucHolidays = ucHolidays;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ucCalendar", cascade ={CascadeType.REMOVE})
    public Set<UcPatternRecord> getUcPatternRecords() {
        return this.ucPatternRecords;
    }

    public void setUcPatternRecords(Set<UcPatternRecord> ucPatternRecords) {
        this.ucPatternRecords = ucPatternRecords;
    }

    @Column(name = "siteId", length = 36)
    public String getSiteId() {
        return siteId;
    }

    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }

    @Column(name = "orgId", length = 36)
    public String getOrgId() {
        return orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }


}


