package com.energicube.eno.calendar.model;
// Generated 2013-8-21 16:23:12 by Hibernate Tools 3.4.0.CR1


import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.util.Date;

/**
 * UcWeather generated by hbm2java
 */
@Entity
@Table(name = "UC_weather"
        , schema = "zclfsys"
)
public class UcWeather implements java.io.Serializable {


    private String id;
    @org.codehaus.jackson.annotate.JsonBackReference
    @com.fasterxml.jackson.annotation.JsonBackReference
    private UcCalendar ucCalendar;
    private String weather;
    private String weatherDescription;
    private String temperature;
    private Integer minTemperature;
    private Integer maxTemperature;
    private String humidity;
    private String sunrise;
    private String sunset;

    private Date issueTime;
    private String weatherIcon;
    private String weatherType;
    private String airPressure;
    private String windDir;
    private String windSpeed;
    private String rain;
    private String snow;
    private String fog;
    private String solarradiation;
    private String isNew;

    public UcWeather() {
    }


    public UcWeather(String id) {
        this.id = id;
    }


    @Id

    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
    @Column(name = "id", unique = true, nullable = false, length = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.DETACH)
    @JoinColumn(name = "calendarId")
    public UcCalendar getUcCalendar() {
        return this.ucCalendar;
    }

    public void setUcCalendar(UcCalendar ucCalendar) {
        this.ucCalendar = ucCalendar;
    }


    @Column(name = "weather", length = 50)
    public String getWeather() {
        return this.weather;
    }

    public void setWeather(String weather) {
        this.weather = weather;
    }

    @Column(name = "weatherDescription", length = 50)
    public String getWeatherDescription() {
        return weatherDescription;
    }

    public void setWeatherDescription(String weatherDescription) {
        this.weatherDescription = weatherDescription;
    }

    @Column(name = "temperature", length = 50)
    public String getTemperature() {
        return this.temperature;
    }

    public void setTemperature(String temperature) {
        this.temperature = temperature;
    }


    @Column(name = "minTemperature")
    public Integer getMinTemperature() {
        return this.minTemperature;
    }

    public void setMinTemperature(Integer minTemperature) {
        this.minTemperature = minTemperature;
    }


    @Column(name = "maxTemperature")
    public Integer getMaxTemperature() {
        return this.maxTemperature;
    }

    public void setMaxTemperature(Integer maxTemperature) {
        this.maxTemperature = maxTemperature;
    }


    @Column(name = "humidity", length = 10)
    public String getHumidity() {
        return this.humidity;
    }

    public void setHumidity(String humidity) {
        this.humidity = humidity;
    }


    @Column(name = "sunrise", length = 10)
    public String getSunrise() {
        return this.sunrise;
    }

    public void setSunrise(String sunrise) {
        this.sunrise = sunrise;
    }


    @Column(name = "sunset", length = 10)
    public String getSunset() {
        return this.sunset;
    }

    public void setSunset(String sunset) {
        this.sunset = sunset;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "issueTime", length = 23)
    public Date getIssueTime() {
        return issueTime;
    }

    public void setIssueTime(Date issueTime) {
        this.issueTime = issueTime;
    }

    @Column(name = "weatherIcon", length = 50)
    public String getWeatherIcon() {
        return weatherIcon;
    }

    public void setWeatherIcon(String weatherIcon) {
        this.weatherIcon = weatherIcon;
    }

    @Column(name = "weatherType", length = 4)
    public String getWeatherType() {
        return weatherType;
    }

    public void setWeatherType(String weatherType) {
        this.weatherType = weatherType;
    }

    @Column(name = "airPressure", length = 10)
    public String getAirPressure() {
        return airPressure;
    }

    public void setAirPressure(String airPressure) {
        this.airPressure = airPressure;
    }

    @Column(name = "windDir", length = 30)
    public String getWindDir() {
        return windDir;
    }

    public void setWindDir(String windDir) {
        this.windDir = windDir;
    }

    @Column(name = "windSpeed", length = 10)
    public String getWindSpeed() {
        return windSpeed;
    }

    public void setWindSpeed(String windSpeed) {
        this.windSpeed = windSpeed;
    }

    @Column(name = "rain", length = 10)
    public String getRain() {
        return rain;
    }

    public void setRain(String rain) {
        this.rain = rain;
    }

    @Column(name = "snow", length = 10)
    public String getSnow() {
        return snow;
    }

    public void setSnow(String snow) {
        this.snow = snow;
    }

    @Column(name = "fog", length = 10)
    public String getFog() {
        return fog;
    }

    public void setFog(String fog) {
        this.fog = fog;
    }

    @Column(name = "solarradiation", length = 10)
    public String getSolarradiation() {
        return solarradiation;
    }

    public void setSolarradiation(String solarradiation) {
        this.solarradiation = solarradiation;
    }

    @Column(name = "isNew", length = 4)
    public String getIsNew() {
        return isNew;
    }

    public void setIsNew(String aNew) {
        isNew = aNew;
    }

    @Override
    public String toString() {
        return "UcWeather{" +
                "id='" + id + '\'' +
                ", ucCalendar=" + ucCalendar +
                ", weather='" + weather + '\'' +
                ", weatherDescription='" + weatherDescription + '\'' +
                ", temperature='" + temperature + '\'' +
                ", minTemperature=" + minTemperature +
                ", maxTemperature=" + maxTemperature +
                ", humidity='" + humidity + '\'' +
                ", sunrise='" + sunrise + '\'' +
                ", sunset='" + sunset + '\'' +
                ", issueTime=" + issueTime +
                ", weatherIcon='" + weatherIcon + '\'' +
                ", weatherType='" + weatherType + '\'' +
                ", airPressure='" + airPressure + '\'' +
                ", windDir='" + windDir + '\'' +
                ", windSpeed='" + windSpeed + '\'' +
                ", rain='" + rain + '\'' +
                ", snow='" + snow + '\'' +
                ", fog='" + fog + '\'' +
                ", solarradiation='" + solarradiation + '\'' +
                ", isNew='" + isNew + '\'' +
                '}';
    }
}


