package com.energicube.eno.pattern.model;

// Generated 2013-8-21 16:23:12 by Hibernate Tools 3.4.0.CR1

import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * UcCombinationPattern generated by hbm2java
 */
@Entity
@Table(name = "UC_combinationPattern", schema = "zclfsys")
public class UcCombinationPattern implements java.io.Serializable {

    private String id;
    @org.codehaus.jackson.annotate.JsonBackReference
    @com.fasterxml.jackson.annotation.JsonBackReference
    private UcGlobalPattern ucGlobalPattern;
    @org.codehaus.jackson.annotate.JsonBackReference
    @com.fasterxml.jackson.annotation.JsonBackReference
    private UcPattern ucPattern;
    private Integer baseTime;
    private Integer offsetTime;
    private String description;
    private String systemId;

    public UcCombinationPattern() {
    }

    public UcCombinationPattern(String id) {
        this.id = id;
    }

    public UcCombinationPattern(String id, UcGlobalPattern ucGlobalPattern,
                                UcPattern ucPattern, Integer baseTime, Integer offsetTime,
                                String description) {
        this.id = id;
        this.ucGlobalPattern = ucGlobalPattern;
        this.ucPattern = ucPattern;
        this.baseTime = baseTime;
        this.offsetTime = offsetTime;
        this.description = description;
    }

    @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
    @Column(name = "id", unique = true, nullable = false, length = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY,cascade = CascadeType.DETACH)
    @JoinColumn(name = "globalPatternId")
    public UcGlobalPattern getUcGlobalPattern() {
        return this.ucGlobalPattern;
    }

    public void setUcGlobalPattern(UcGlobalPattern ucGlobalPattern) {
        this.ucGlobalPattern = ucGlobalPattern;
    }

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.DETACH)
    @JoinColumn(name = "patternId")
    public UcPattern getUcPattern() {
        return this.ucPattern;
    }

    public void setUcPattern(UcPattern ucPattern) {
        this.ucPattern = ucPattern;
    }

    @Column(name = "baseTime")
    public Integer getBaseTime() {
        return this.baseTime;
    }

    public void setBaseTime(Integer baseTime) {
        this.baseTime = baseTime;
    }

    @Column(name = "offsetTime")
    public Integer getOffsetTime() {
        return this.offsetTime;
    }

    public void setOffsetTime(Integer offsetTime) {
        this.offsetTime = offsetTime;
    }

    @Column(name = "description", length = 200)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "systemId", length = 36)
    public String getSystemId() {
        return systemId;
    }

    public void setSystemId(String systemId) {
        this.systemId = systemId;
    }

    @Override
    public String toString() {
        return "UcCombinationPattern{" +
                "id='" + id + '\'' +
                ", ucGlobalPattern=" + ucGlobalPattern +
                ", ucPattern=" + ucPattern +
                ", baseTime=" + baseTime +
                ", offsetTime=" + offsetTime +
                ", description='" + description + '\'' +
                ", systemId='" + systemId + '\'' +
                '}';
    }
}
