package com.energicube.eno.pattern.model;
// Generated 2013-8-21 16:23:12 by Hibernate Tools 3.4.0.CR1


import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UcFactor generated by hbm2java
 */
@Entity
@Table(name = "UC_factor"
        , schema = "zclfsys"
)
public class UcFactor implements java.io.Serializable {


    private String id;
    private String name;
    private String minValue;
    private String maxValue;
    private Date startDate;
    private Date endDate;
    private String description;
    private String parentId;
    private String factorType;
    @org.codehaus.jackson.annotate.JsonBackReference
    @com.fasterxml.jackson.annotation.JsonBackReference
    private Set<UcPatternFactor> ucPatternFactors = new HashSet<UcPatternFactor>(0);
    @org.codehaus.jackson.annotate.JsonBackReference
    @com.fasterxml.jackson.annotation.JsonBackReference
    private Set<UcSysFactor> ucSysFactors = new HashSet<UcSysFactor>(0);

    public UcFactor() {
    }


    public UcFactor(String id) {
        this.id = id;
    }

    public UcFactor(String id, String name, String minValue, String maxValue, Date startDate, Date endDate, String description, String parentId, String factorType, Set<UcPatternFactor> ucPatternFactors, Set<UcSysFactor> ucSysFactors) {
        this.id = id;
        this.name = name;
        this.minValue = minValue;
        this.maxValue = maxValue;
        this.startDate = startDate;
        this.endDate = endDate;
        this.description = description;
        this.parentId = parentId;
        this.factorType = factorType;
        this.ucPatternFactors = ucPatternFactors;
        this.ucSysFactors = ucSysFactors;
    }

    @Id

    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
    @Column(name = "id", unique = true, nullable = false, length = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }


    @Column(name = "name", length = 60)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }


    @Column(name = "minValue", length = 60)
    public String getMinValue() {
        return this.minValue;
    }

    public void setMinValue(String minValue) {
        this.minValue = minValue;
    }


    @Column(name = "maxValue", length = 60)
    public String getMaxValue() {
        return this.maxValue;
    }

    public void setMaxValue(String maxValue) {
        this.maxValue = maxValue;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "startDate", length = 23)
    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "endDate", length = 23)
    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }


    @Column(name = "description", length = 60)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }


    @Column(name = "parentId", length = 36)
    public String getParentId() {
        return this.parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }


    @Column(name = "factorType", length = 4)
    public String getFactorType() {
        return this.factorType;
    }

    public void setFactorType(String factorType) {
        this.factorType = factorType;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ucFactor" ,cascade ={CascadeType.DETACH})
    public Set<UcPatternFactor> getUcPatternFactors() {
        return this.ucPatternFactors;
    }

    public void setUcPatternFactors(Set<UcPatternFactor> ucPatternFactors) {
        this.ucPatternFactors = ucPatternFactors;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ucFactor", cascade ={CascadeType.DETACH})
    public Set<UcSysFactor> getUcSysFactors() {
        return this.ucSysFactors;
    }

    public void setUcSysFactors(Set<UcSysFactor> ucSysFactors) {
        this.ucSysFactors = ucSysFactors;
    }


}


