package com.energicube.eno.pattern.model;
// Generated 2013-8-21 16:23:12 by Hibernate Tools 3.4.0.CR1


import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UcGlobalPattern generated by hbm2java
 */
@Entity
@Table(name = "UC_globalPattern"
        
)
public class UcGlobalPattern implements java.io.Serializable {


    private String id;
    private String version;
    private String patternName;
    private String patternDescription;
    private String patternType;
    private String systemId;
    private String isNew;
    private String createUser;
    private Date createDate;
    private String siteId;
    private String orgId;
    private String orderType;
    private Set<UcCombinationPattern> ucCombinationPatterns = new HashSet<UcCombinationPattern>(0);

    public UcGlobalPattern() {
    }


    public UcGlobalPattern(String id) {
        this.id = id;
    }

    public UcGlobalPattern(String id, String patternName, String patternDescription, String patternType, String systemId, String isNew, String createUser, Date createDate, Set<UcCombinationPattern> ucCombinationPatterns) {
        this.id = id;
        this.patternName = patternName;
        this.patternDescription = patternDescription;
        this.patternType = patternType;
        this.systemId = systemId;
        this.isNew = isNew;
        this.createUser = createUser;
        this.createDate = createDate;
        this.ucCombinationPatterns = ucCombinationPatterns;
    }

    @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
    @Column(name = "id", unique = true, nullable = false, length = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }


    @Column(name = "version", length = 50)
    public String getVersion() {
        return this.version;
    }

    public void setVersion(String version) {
        this.version = version;
    }


    @Column(name = "patternName", length = 60)
    public String getPatternName() {
        return this.patternName;
    }

    public void setPatternName(String patternName) {
        this.patternName = patternName;
    }


    @Column(name = "patternDescription", length = 100)
    public String getPatternDescription() {
        return patternDescription;
    }

    public void setPatternDescription(String patternDescription) {
        this.patternDescription = patternDescription;
    }


    @Column(name = "patternType", length = 4)
    public String getPatternType() {
        return this.patternType;
    }

    public void setPatternType(String patternType) {
        this.patternType = patternType;
    }


    @Column(name = "systemId", length = 36)
    public String getSystemId() {
        return this.systemId;
    }

    public void setSystemId(String systemId) {
        this.systemId = systemId;
    }


    @Column(name = "isNew", length = 4)
    public String getIsNew() {
        return this.isNew;
    }

    public void setIsNew(String isNew) {
        this.isNew = isNew;
    }


    @Column(name = "createUser", length = 50)
    public String getCreateUser() {
        return this.createUser;
    }

    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "createDate", length = 23)
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ucGlobalPattern",  cascade ={CascadeType.REMOVE,CascadeType.DETACH})
    public Set<UcCombinationPattern> getUcCombinationPatterns() {
        return this.ucCombinationPatterns;
    }

    public void setUcCombinationPatterns(Set<UcCombinationPattern> ucCombinationPatterns) {
        this.ucCombinationPatterns = ucCombinationPatterns;
    }

    @Column(name = "siteId", length = 36)
    public String getSiteId() {
        return siteId;
    }

    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }

    @Column(name = "orgId", length = 36)
    public String getOrgId() {
        return orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }

    @Column(name = "orderType", length = 4)
    public String getOrderType() {
        return orderType;
    }

    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }
}


