package com.energicube.eno.pattern.model;
// Generated 2013-8-21 16:23:12 by Hibernate Tools 3.4.0.CR1


import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;

/**
 * UcPatternFactor generated by hbm2java
 */
@Entity
@Table(name = "UC_patternFactor"
        
)
public class UcPatternFactor implements java.io.Serializable {


    private String id;
    @org.codehaus.jackson.annotate.JsonBackReference
    @com.fasterxml.jackson.annotation.JsonBackReference
    private UcPattern ucPattern;
    @org.codehaus.jackson.annotate.JsonBackReference
    @com.fasterxml.jackson.annotation.JsonBackReference
    private UcFactor ucFactor;
    private String note;

    public UcPatternFactor() {
    }


    public UcPatternFactor(String id) {
        this.id = id;
    }

    public UcPatternFactor(String id, UcPattern ucPattern, UcFactor ucFactor, String note) {
        this.id = id;
        this.ucPattern = ucPattern;
        this.ucFactor = ucFactor;
        this.note = note;
    }

    @Id
    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
    @Column(name = "id", unique = true, nullable = false, length = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER,cascade = CascadeType.DETACH)
    @JoinColumn(name = "patternId")
    public UcPattern getUcPattern() {
        return this.ucPattern;
    }

    public void setUcPattern(UcPattern ucPattern) {
        this.ucPattern = ucPattern;
    }

    @ManyToOne(fetch = FetchType.EAGER,cascade = CascadeType.DETACH)
    @JoinColumn(name = "factorId")
    public UcFactor getUcFactor() {
        return this.ucFactor;
    }

    public void setUcFactor(UcFactor ucFactor) {
        this.ucFactor = ucFactor;
    }


    @Column(name = "note", length = 60)
    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }


}


