package com.energicube.eno.pattern.model;
// Generated 2013-8-21 16:23:12 by Hibernate Tools 3.4.0.CR1


import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.util.HashSet;
import java.util.Set;

/**
 * UcPatternAction generated by hbm2java
 */
@Entity
@Table(name = "UC_patternAction"
        , schema = "zclfsys"
)
public class UcPatternAction implements java.io.Serializable {


    private String id;

    @org.codehaus.jackson.annotate.JsonBackReference
    @com.fasterxml.jackson.annotation.JsonBackReference
    private UcPattern ucPattern;
    private Integer baseTime;
    private Integer offsetTime;
    private Integer relativeTime;
    private String description;
    private String actionType;
    private Set<UcDevicePattern> ucDevicePatterns = new HashSet<UcDevicePattern>(0);

    public UcPatternAction() {
    }


    public UcPatternAction(String id) {
        this.id = id;
    }

    public UcPatternAction(String id, UcPattern ucPattern, Integer baseTime, Integer offsetTime, Integer relativeTime, String description, String actionType, Set<UcDevicePattern> ucDevicePatterns) {
        this.id = id;
        this.ucPattern = ucPattern;
        this.baseTime = baseTime;
        this.offsetTime = offsetTime;
        this.relativeTime = relativeTime;
        this.description = description;
        this.actionType = actionType;
        this.ucDevicePatterns = ucDevicePatterns;
    }

    @Id

    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
    @Column(name = "id", unique = true, nullable = false, length = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY,cascade = CascadeType.DETACH)
    @JoinColumn(name = "patternId")
    public UcPattern getUcPattern() {
        return this.ucPattern;
    }

    public void setUcPattern(UcPattern ucPattern) {
        this.ucPattern = ucPattern;
    }


    @Column(name = "baseTime")
    public Integer getBaseTime() {
        return this.baseTime;
    }

    public void setBaseTime(Integer baseTime) {
        this.baseTime = baseTime;
    }


    @Column(name = "offsetTime")
    public Integer getOffsetTime() {
        return this.offsetTime;
    }

    public void setOffsetTime(Integer offsetTime) {
        this.offsetTime = offsetTime;
    }


    @Column(name = "relativeTime")
    public Integer getRelativeTime() {
        return this.relativeTime;
    }

    public void setRelativeTime(Integer relativeTime) {
        this.relativeTime = relativeTime;
    }


    @Column(name = "description")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }


    @Column(name = "actionType", length = 4)
    public String getActionType() {
        return this.actionType;
    }

    public void setActionType(String actionType) {
        this.actionType = actionType;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ucPatternAction",  cascade ={CascadeType.REMOVE,CascadeType.DETACH})
    public Set<UcDevicePattern> getUcDevicePatterns() {
        return this.ucDevicePatterns;
    }

    public void setUcDevicePatterns(Set<UcDevicePattern> ucDevicePatterns) {
        this.ucDevicePatterns = ucDevicePatterns;
    }


    @Override
    public String toString() {
        return "UcPatternAction{" +
                "id='" + id + '\'' +
                ", ucPattern=" + ucPattern +
                ", baseTime=" + baseTime +
                ", offsetTime=" + offsetTime +
                ", relativeTime=" + relativeTime +
                ", description='" + description + '\'' +
                ", actionType='" + actionType + '\'' +
                ", ucDevicePatterns=" + ucDevicePatterns +
                '}';
    }
}


