package com.energicube.eno.pattern.model;

import org.hibernate.annotations.GenericGenerator;

import javax.persistence.*;
import java.util.Date;

/**
 * UcSystemBusinessTime generated by hbm2java
 */
@Entity
@Table(name = "UC_systemBusinessTime"
        , schema = "zclfsys"
)
public class UcSystemBusinessTime implements java.io.Serializable {


    private String id;
    private Date startDate;
    private Date endDate;
    private Date openTime;
    private Date closeTime;
    private String description;
    private String siteId;
    private String orgId;

    public UcSystemBusinessTime() {
    }


    public UcSystemBusinessTime(String id) {
        this.id = id;
    }

    public UcSystemBusinessTime(String id, Date startDate, Date endDate, Date openTime, Date closeTime, String description, String siteId, String orgId) {
        this.id = id;
        this.startDate = startDate;
        this.endDate = endDate;
        this.openTime = openTime;
        this.closeTime = closeTime;
        this.description = description;
        this.siteId = siteId;
        this.orgId = orgId;
    }

    @Id

    @GeneratedValue(generator = "system-uuid")
    @GenericGenerator(name = "system-uuid", strategy = "uuid.hex")
    @Column(name = "id", unique = true, nullable = false, length = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "startDate", length = 23)
    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "endDate", length = 23)
    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "openTime", length = 16)
    public Date getOpenTime() {
        return this.openTime;
    }

    public void setOpenTime(Date openTime) {
        this.openTime = openTime;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "closeTime", length = 16)
    public Date getCloseTime() {
        return this.closeTime;
    }

    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }


    @Column(name = "description", length = 30)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }


    @Column(name = "siteId", length = 36)
    public String getSiteId() {
        return this.siteId;
    }

    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }


    @Column(name = "orgId", length = 36)
    public String getOrgId() {
        return this.orgId;
    }

    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }


}


